services:
  db:
    image: mysql:8.0
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: satoshi_exchange
    command:
      [
        'mysqld',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
      ]

  go:
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/se-api
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_DATABASE: satoshi_exchange
      DB_USERNAME: root
      DB_PASSWORD: secret
      GOOGLE_APPLICATION_CREDENTIALS: /se-api/serviceAccountKey.json

volumes:
  db-data:
